[build]
  command = "npm install && npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables are set directly in Netlify dashboard
# DATABASE_URL, AUTH_SECRET, NEXTAUTH_URL, SEED_ADMIN_PASSWORD
