[build]
  command = "prisma migrate deploy && next build"
  publish = ".next"

# Environment variables are now set directly in Netlify dashboard
# No need to override here since DATABASE_URL will be set directly
