[build]
  command = "prisma migrate deploy && next build"
  publish = ".next"

[context.production.environment]
  DATABASE_URL = "${NETLIFY_DATABASE_URL}"

[context.deploy-preview.environment]
  DATABASE_URL = "${NETLIFY_DATABASE_URL}"

[context.branch-deploy.environment]
  DATABASE_URL = "${NETLIFY_DATABASE_URL}"
